#!/bin/sh

set -e
#set -x

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql 
dbc_generate_include=template:/etc/dataware/energy_config.cfg
dbc_generate_include_args="-o template_infile=/usr/share/pyshared/dataware-energy/config.cfg"
dbc_go dataware-energy $@

#DEBHELPER#
