#!/bin/sh
java -classpath .:/usr/share/java/currentcost-energy-monitor.jar:/usr/share/java/mysql-connector-java.jar:/usr/share/java/RXTXcomm.jar uk/ac/nott/cs/txl/energy/Monitor $1 & 
echo -n $! " " >> /var/run/energymonitor.pid
